### PR TITLE
Added dynamic timestep safety, ensures heating events aren't overstepped

### PR DESCRIPTION
**Pull request by schonfsj**
I wrote a function in heater.cpp and propagated it through loop.cpp into main.cpp to check how much time there is until the next change in the heating function (i.e. the next start or end of a heating rise or decay). I then applied this as another upper limit to the dynamic timestep size, ensuring that the model is run at each one of these "nodes" in the heating function. Functionally, this check involves a loop through all the heating events at each timestep, so it's perhaps not the most efficient method. The algorithm was modeled after Get_Heater() in heater.cpp.

The purpose of this change is to ensure that the model cannot skip heating events entirely when using a dynamic timestep. Without this check, if tau_max is large enough and the heating event is short enough, it is possible for the model to completely "skip over" and ignore individual heating events. Forcing the model to evaluate at each "node" of the heating function ensures that all heating events are properly incorporated into the model.

P.S. My apologies for the clutter of the meaningless additions and subtractions. Those changes were not intentional.

### CODE REVIEW

**Comment by wtbarnes** [comment]
This is great! I'm very much in favor of this addition as I've been bitten by this before, particularly if you've got a long period prior to a heating time step.

Given, as you say, that this can make things much slower due to the need to loop over every heating event at each timestep, I wonder if it would make sense to add a flag to toggle this on and off. I'm not sure of a good name for this: maybe `check_heating_timestep`?

**Comment by wtbarnes** [comment]
Would you also mind plotting the difference in timestep (as a function of time) with and without this option? I am curious to see what the effect is across a simulation.

**Comment by schonfsj** [comment]
I'm happy to hear the enthusiasm!

Per your second comment, here's the output of the test case I've been using without these changes:
image

And here's what happens when adding this new timestep check:
image

For completeness, here are some runs with pseudo-random heating with the original scheme:
image

And with the timestep check:
image

In all of these runs, tau_max = 10,000 seconds. Looking at the first two runs, it's clear that there are a bunch of extra timesteps when a heating event is not skipped, as would be expected. Counterintuitively, looking at the last two runs, this additional check actually results in fewer timesteps. With this heating, forcing the model to evaluate at each heating "node" results in a reduction from 1020 to 599 timesteps. If I had to guess, this is probably because forcing the timestep at the discontinuity in the heating function results in the minimum "overshoot," but I'm not confident about that interpretation as I don't think I really understand the boost stepper completely. On the plus side, I'm not seeing any obvious distortion in the plasma response between the two versions, so the science results should be consistent.

As for the computational efficiency, upon further reflection, I don't think the hit is meaningful. It's essentially the same as having to calculate the heating with Get_Heating() one additional time per timestep. Since Get_Heating() is called inside CalculateDerivs() which is run in every stepper sub-loop, this is like running through that subloop less than one extra time per timestep. If we wanted to be really sneaky, we could calculate this timestep limit inside Get_Heating(), but I think with how many times that gets called, the extra computations per loop might end up being heavier than just running through the loop one additional iteration per timestep.

Obviously, it's your call. If you do want the flag, I think `check_heating_timestep` is fine.

**Comment by wtbarnes** [comment]
Sorry for the delay here @schonfsj. I think this looks good and I think I agree with your statement re: why there are actually fewer timesteps in the second case. It seems that your correction here is more moderate and by making more moderate corrections more frequently, it stops the adaptive stepper from making more extreme corrections less frequently. I've not dug in to the code to verify this, but it seems reasonable. It's been a long time since I thought about the details of how the adaptive time stepping works here!

Your changes look good to me, but before this gets merged, I'd like to get the tests running again on the CI and the docs building again. The automatic builds are a bit of a mess because I've not yet switched everything over to GitHub Actions. Once that is done (hopefully very soon!) I can just rebase your PR, make sure all the tests pass (and maybe add a new one with this option turned on) and then we should be good.

Again, sorry for the delay here. I've let this project fall by the wayside in the past few years!

**Comment by schonfsj** [comment]
That all sounds good, @wtbarnes. I'm fully in favor of fixing up the CI tests before merging this new functionality.

And no worries about the delays. I was going to ping you about it eventually, but clearly, I also have lots of other things going on.

**Comment by wtbarnes** [comment]
Ok I've finally fixed the CI on `main` so it should be ready to be applied to this PR. As you have time, would you mind addressing the following:

1. Rebase this PR on top of main. There shouldn't be any conflicts as I've not modified any of the files you've modified in this PR and this should start the CI running on this PR.
2. Could you add a toggle for using this timestepping scheme? 
3. Could you add a test that compares results with and without the timestepping scheme and tests that they are the same (within some tolerance)? The [`test_solver.py`](https://github.com/rice-solar-physics/ebtelPlusPlus/blob/main/tests/test_solver.py) should provide a decent template on how to do this.

Feel free to let me know if you have any questions about any of those steps. I'm also happy to wrap this up if you feel like you don't have the time at the moment.

**Review by wtbarnes — APPROVED** [review]
Sorry this took so long @schonfsj. Given that all of the tests pass, I'm going to go ahead and merge this as is. Thinking about it some more, it seems to me that a heating event being skipped (as could happen without this PR) should be regarded as a bug so it does not make much sense to have a switch to turn this behavior off.

**Comment by schonfsj** [comment]
@wtbarnes, absolutely no need to apologize. This was on my to-do list, I just never quite got around to it and completely failed to communicate with you. Thank you for taking over and testing it for me.

**Pull request merged**
